### ISSUE TITLE
Cleaning Out Unwanted Files

### ISSUE THREAD

**Issue by devanshuyadav** [devanshuyadav/helpage#48]

**Comment by shikhar13012001** [comment]
Could you please provide some description? I would like to work on this

**Comment by devanshuyadav** [comment]
There are some unwanted files in this repo that are just crowding it. If you want to work on it you'll have to **`Accurately`** identify those files and delete them.

**Comment by shikhar13012001** [comment]
Alright I am going to try for it.

**Comment by devanshuyadav** [comment]
cool! I'll assign this to you. Don't Mess up!

**Comment by shikhar13012001** [comment]
Can you please review my PR ?😅😅
